'use client';
import Image from 'next/image';
import Link from 'next/link';
import { useRouter } from 'next/navigation';
import { useState } from 'react';
import { ArrowRight, ArrowUpRight, CalendarDays, GitBranch, Plus, ShieldCheck, Sparkles, Wallet, Plane, CarFront, Hotel, Music2 } from 'lucide-react';
import { useTrip } from './trip-provider';
import { TripHealth } from './trip-health';
import { Timeline } from './timeline';
import { DependencyGraph } from './dependency-graph';
import { formatMoney } from '../engine/recover';
import { analyzeJourney } from '../engine/journey';
import { Copilot } from './copilot';
import { baseline } from '../fixtures/trip';

export function PageHeading({ eyebrow, title, description, children }: { eyebrow: string; title: string; description: string; children?: React.ReactNode }) { return <div className="product-page-heading"><div><p className="eyebrow">{eyebrow}</p><h1>{title}</h1><p>{description}</p></div>{children}</div>; }
export function LoadingTrip() { return <div className="empty-card" role="status"><Sparkles /><h2>Connecting your journey…</h2><p>Your saved trip will appear in a moment.</p></div>; }
export function HomePage() {
  const [paused, setPaused] = useState(false);
  const { data, mutate, busy } = useTrip(); const router = useRouter();
  async function demo() { if (data?.state.mode === 'personal' && data.state.bookings?.length && !window.confirm('Replace this browser’s personal itinerary with the fictional Goa demo? Cancel to keep your current trip.')) return; if (await mutate({ action: 'reset' })) router.push('/itinerary'); }
  const count = data?.state.applied?.segments.length ?? data?.recovery.timeline.length ?? 0;
  return <div className={`motion-home ${paused ? 'motion-paused' : ''}`}>
    <div className="home-intro"><p className="eyebrow">TRAVEL WITH A WAY FORWARD</p><button className="motion-control" aria-pressed={paused} onClick={() => setPaused(!paused)}>{paused ? 'Play motion' : 'Pause motion'}</button></div>
    <section className="home-hero"><div className="home-hero-copy"><span className="hero-kicker"><GitBranch size={16} /> Every connection. Considered.</span><h1>Plans change.<br /><em>Your trip can go on.</em></h1><p>When one booking changes, see what breaks next—and find a way to save the moments that matter.</p><div className="hero-actions"><button className="button primary" disabled={busy || !data} onClick={demo}>Try demo scenario <ArrowRight size={17} /></button><Link href="/add-itinerary" className="button outline"><Plus size={17} /> Add my itinerary</Link></div><small>Explore Mumbai–Goa, or build a trip of your own.</small></div><div className="home-art"><Image src="/images/goa-coast.png" alt="Palm-lined Goa coastline overlooking the sea" fill priority sizes="(max-width: 800px) 100vw, 50vw" /><div className="art-note"><span>THE DESTINATION IS STILL YOURS</span><strong>A little less worry.<br /><em>A lot more wonder.</em></strong><small>GOA, INDIA · DEMO JOURNEY</small></div></div></section>
    <div className="home-dashboard"><TripHealth /><section className="overview-card"><div className="section-heading"><div><p className="eyebrow">YOUR JOURNEY, AT A GLANCE</p><h2>{data?.state.mode === 'personal' ? 'Your personal itinerary' : 'Mumbai → Goa'}</h2></div><Link href="/itinerary" aria-label="Open itinerary"><ArrowUpRight /></Link></div><div className="overview-stats"><div><strong>{count}</strong><span>Connected stops</span></div><div><strong>{data?.recovery.timeline.some(s => s.durationUnknown || s.locationUnknown) ? 'Needs details' : data?.state.applied ? 'Planned' : data?.state.disruption || data?.state.scenario !== 'original' ? 'Review' : 'Ready'}</strong><span>Journey status</span></div></div><p>Your itinerary, connections, and recovery options use the same saved trip.</p><Link href="/itinerary" className="text-button">Open my itinerary <ArrowRight size={16} /></Link></section></div>
    {data && data.state.mode !== 'personal' && !data.state.applied && !data.state.disruption && <Copilot scenario={data.state.scenario} busy={busy} onApply={async draft => { const saved = await mutate({ action: 'copilot', ...draft }); if (saved) router.push('/recovery'); return saved; }} />}
    <section className="concept-panel"><div><p className="eyebrow">SMALL CHANGE. CONNECTED CONSEQUENCES.</p><h2>See the whole journey,<br /><em>and every connection.</em></h2><p>Explore the dependencies before you need a backup plan.</p><Link href="/dependencies" className="text-button">Explore connections <ArrowRight size={16} /></Link></div><div className="concept-chain" aria-label="Illustration of a flight connected to a cab, hotel and event">{[[Plane, 'Flight'], [CarFront, 'Cab'], [Hotel, 'Hotel'], [Music2, 'Event']].map(([Icon, label], i) => { const I = Icon as typeof Plane; return <div key={String(label)} style={{ '--step': i } as React.CSSProperties}><I size={24} /><strong>{String(label)}</strong><span>{i === 0 ? 'One delay…' : i === 3 ? 'Protect this moment' : 'Check the connection'}</span></div>; })}<small>Illustration only · run a scenario to see calculated impacts</small></div></section>
    <div className="feature-links"><Link href="/dependencies"><GitBranch /><h3>Every connection counts</h3><p>Actual buffers, useful guidance, and the cause behind each risk.</p><ArrowUpRight /></Link><Link href="/what-if"><Sparkles /><h3>Ask “what if?” first</h3><p>Explore a disruption without changing your saved itinerary.</p><ArrowUpRight /></Link><Link href="/recovery"><ShieldCheck /><h3>Keep what matters</h3><p>Compare the timing, cost, and tradeoffs of a recovery.</p><ArrowUpRight /></Link></div>
  </div>;
}
export function ItineraryPage() {
  const { data } = useTrip(); if (!data) return <LoadingTrip />;
  const { state, recovery } = data; const segments = state.applied?.segments ?? recovery.timeline;
  const cost = (state.mode === 'personal' ? state.bookings ?? [] : baseline()).reduce((sum, s) => sum + (s.cost ?? 0), 0) + (state.applied?.ledger.cashNow ?? 0); const allCostsUnknown = state.mode === 'personal' && segments.every(s => s.cost === undefined); const risks = recovery.impacts.filter(i => i.state !== 'unaffected').length;
  return <><PageHeading eyebrow="YOUR TRIP COMMAND CENTER" title="Every stop. One journey." description="Your timings, priorities, and connected plans in one place."><Link className="button primary" href="/add-itinerary"><Plus size={17} /> Add / edit itinerary</Link></PageHeading><div className="itinerary-top"><TripHealth compact /><div className="trip-metrics"><div><CalendarDays /><strong>{segments.length}</strong><span>Itinerary items</span></div><div><Wallet /><strong>{allCostsUnknown ? 'Not supplied' : formatMoney(cost)}</strong><span>{state.applied ? 'Total planned cost' : state.mode === 'personal' ? 'Entered cost subtotal' : 'Total booking cost'}</span></div><div><ShieldCheck /><strong>{state.mode === 'personal' ? segments.filter(s => s.priority).length : state.preferences.protectOriginal ? 1 : 0}</strong><span>Must-save moments</span></div></div></div><div className="itinerary-layout"><section className="panel itinerary-full"><div className="section-heading"><div><p className="eyebrow">{state.mode === 'personal' ? 'YOUR ENTERED DETAILS' : 'FICTIONAL MUMBAI–GOA DEMO'}</p><h2>My itinerary</h2></div><span className="revision">v{state.revision}</span></div><p className="muted">All times in IST · open a stop for its details</p>{segments.length ? <Timeline segments={segments} impacts={recovery.impacts} applied={!!state.applied} /> : <div className="empty-card"><h3>Your next journey starts here.</h3><Link href="/add-itinerary" className="button primary">Add your first booking</Link></div>}<Link href="/add-itinerary" className="button outline">Edit booking details <ArrowRight size={15} /></Link></section><aside className="itinerary-aside"><section className="overview-card"><p className="eyebrow">CONNECTION WATCH</p><h2>{state.applied ? 'Recovery itinerary saved' : `${risks} items to keep an eye on`}</h2><p>{state.applied ? 'Review the revised timing. Supplier confirmations are still pending.' : recovery.warning}</p><Link href="/dependencies" className="text-button">Inspect dependencies <ArrowRight size={15} /></Link></section><section className="teal-card"><Sparkles /><h2>Better to ask before<br /><em>the trip asks you.</em></h2><p>Test delays and cancellations in a safe preview.</p><Link href="/what-if" className="button">Open What-if <ArrowRight size={16} /></Link></section></aside></div></>;
}
export function DependenciesPage() { const { data } = useTrip(); if (!data) return <LoadingTrip />; const segments = data.state.applied?.segments ?? data.recovery.timeline; const result = data.state.applied ? analyzeJourney(segments) : data.recovery; return <><PageHeading eyebrow="THE CONNECTIONS BEHIND YOUR TRIP" title="One change. A ripple through the day." description="Hover, focus, or open a stop to understand its dependencies. Every buffer comes from your itinerary."><Link href="/recovery" className="button primary">Simulate disruption <ArrowRight size={16} /></Link></PageHeading><div className="dependency-layout"><DependencyGraph segments={segments} recovery={result} applied={!!data.state.applied} /><aside><TripHealth compact /><section className="overview-card"><h3>Booking status</h3><p><span className="legend-dot safe"/> Green · on schedule</p><p><span className="legend-dot tight"/> Yellow · directly affected</p><p><span className="legend-dot risky"/> Red · at risk or blocked</p><h3>Connection buffers</h3><p><span className="legend-dot safe" /> 80%+ · comfortable buffer</p><p><span className="legend-dot tight" /> 50–79% · tight connection</p><p><span className="legend-dot risky" /> Below 50% · review the risk</p><small>Coverage compares available minutes with a planning recommendation. It is not a success probability. No connecting line means no dependency is recorded.</small></section></aside></div></>; }

